[package]
name = "my_tauri_test"
version = "0.1.0"
edition = "2024"
Author = "Adesoji Au"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"